---
title: "data"
author: "Project Team 2"
date: "2024-05-21"
output: html_document
---

#Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
```

## Loading Data

```{r}
data <- read_csv("aggregate_data.csv")
head(data)
```

```{r}
agg_data |> 
  group_by(c_ind_cod_type) |>
  count()

agg_data_cod_covid <- agg_data |> 
  filter(c_ind_cod_type == "COVID-19")

agg_data_cod_covid |> 
  group_by(ind_deathloc) |>
  count()

agg_data |> 
  group_by(c_system_abbr) |> 
  count()
  
```

```{r}

private_manual_incomplete <- prisons_manual_incomplete|> 
  mutate(facility = toupper(facility))

public_manual_incomplete <- public_manual_incomplete |> 
  mutate(facility = toupper(facility))

```

```{r}

priv_not_included <- anti_join(private_manual_incomplete, prisons_hsf, by="hsf_facility_name")
pub_not_included <- anti_join(public_manual_incomplete, prisons_hsf, by="hsf_facility_name")
```

```{r}

#finding missing values in HILFD FacilityID range
setdiff(10000001:	
10007020
, prisons_hsf$V2)
```

#Data Visualization on System-Level Data

```{r}
library(tidyverse)

data <- read_csv("aggregate_data.csv")

ind_cod_dataset <- data %>% 
  select(system, ind_first, ind_last, ind_age, ind_gender, ind_race, ind_deathloc, ind_dod, ind_cod, c_ind_cod_type) %>% 
  count(c_ind_cod_type) 
ind_cod_dataset

ind_cod_dataset %>% 
  ggplot(aes(x = c_ind_cod_type, y = n)) + 
    geom_bar(stat = "identity") +
    geom_text(aes(label = n), vjust = -0.3) +
    labs(title = "Count of Incarcerated Cause of Death Type", x = "Cause of Death Type", y = "Count") + 
    theme_minimal() + 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1)
    ) + 
    scale_y_continuous(limits = c(0, 3000), breaks = c(500, 1000, 1500, 2000, 2500, 3000))

```

#Missing data percentage

```{r}
data %>% 
  summarize(across(everything(), ~mean(is.na(.)) * 100)) %>% 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "data_percentage") %>% 
  mutate(data_percentage = round(data_percentage, 2))
```

#Missing data percentage for each variable

```{r}
comprehensive_percentages <- data %>% 
  group_by(system) %>% 
  summarize(across(everything(), ~sum(!is.na(.))/n() * 100)) %>% 
  summarize(across(everything(), ~mean(. == 100) * 100)) %>% 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "comprehensive_percentage") %>% 
  mutate(comprehensive_percentage = round(comprehensive_percentage, 2)) 
comprehensive_percentages

comprehensive_systems <- data %>% 
  group_by(system) %>% 
  summarize(across(everything(), ~all(!is.na(.)))) %>% 
  pivot_longer(cols = -system, names_to = "variable", values_to = "comprehensive_data") %>% 
  filter(comprehensive_data) %>% 
  group_by(variable) %>% 
  summarize(systems = paste(system, collapse = ", "))
comprehensive_systems

missing_data <- left_join(comprehensive_percentages, comprehensive_systems, by = "variable") 
missing_data
```

#Missing data percentage for each variable by system

```{r}
data %>% 
  group_by(system) %>% 
  summarize(across(everything(), ~mean(is.na(.)) * 100)) %>% 
  pivot_longer(cols = -system, names_to = "variable", values_to = "data_percentage") %>% 
  mutate(data_percentage = round(data_percentage, 2)) %>% 
  pivot_wider(names_from = system, values_from = data_percentage)
```

#Number of deaths reported per facility where the inmate was housed

```{r}
agg_data |>
  group_by(ind_fachoused) |>
  count()
```

#Creates dataset with deaths per facility without NA

```{r}
facility_death_data <- agg_data |>
  filter(!is.na(ind_fachoused)) |>
  group_by(ind_fachoused) |>
  count()
```

#Distribution of number of deaths per facility

```{r}
facility_death_data <- facility_death_data |>
  mutate(dist = case_when(n < 50 ~ '<50',
                          n >= 50 & n <= 100 ~ '51-100',
                          n > 100 & n < 150 ~ '101-150',
                          n > 150 & n < 200 ~ '151-200',
                          n > 200 & n < 250 ~ '201-250',
                          n > 250 & n < 300 ~ '251-300',
                          n > 300 ~ '>300')) |>
  group_by(dist)

view(facility_death_data)
```

```{r}
facility_death_data |>
  mutate(dist = factor(dist, levels = c("<50", "51-100", "101-150", "151-200", "201-250", "251-300", ">300"))) |>
  ggplot(
    aes(x = dist)
  ) +
  geom_bar() +
  labs(title = "Distribution of the Number of Deaths Reported per Facility", 
         x = "Number of Deaths Reported", y = "Number of Facilities")
```

