---
editor_options: 
  markdown: 
    wrap: 72
  output:
  html_document:
    self_contained: false
---

```{r}
#loading packages
library(geojsonR) 
library(sf) 
library(tidyverse) 
library(ggplot2) 
library(here)
library(ggforce)
library(cowplot)
library(patchwork)
```

```{r}
#loading in data 
data_file_path <- here('data', 'aggregate_data.csv')
agg_data <- read_csv(data_file_path)

geo_file_path <- here('data', 'jurisdiction_sf.geojson')
geo_data <- st_read(geo_file_path)

st_crs(geo_data)
```

```{r}
#data wrangling cause of death data pre-join

geo_data <- geo_data |> 
  rename(system = sys_abbr)

cod_agg <- agg_data |> 
  separate(c_ind_dod_ymd, into = c("dod_year", "dod_month", "dod_day"), sep = "-") |>
  filter(dod_year == 2023) |>
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  )) |>
  group_by(c_system_abbr, c_ind_cod_type) |> 
  summarize(count = n()) |>
  mutate(c_ind_cod_type = case_when(
    c_ind_cod_type == "COVID-19" ~ "covid_19",
    c_ind_cod_type == "Drug / Alcohol" ~ "drug_alcohol",
    c_ind_cod_type == "Natural" ~ "natural",
    c_ind_cod_type == "Suicide" ~ "suicide",
    c_ind_cod_type == "Unknown" ~ "unknown",
    c_ind_cod_type == "Execution" ~ "execution",
    c_ind_cod_type == "Homicide" ~ "homicide",
    c_ind_cod_type == "Homicide by LEO" ~ "homicide_by_leo",
    c_ind_cod_type == "Unintentional non-Drug Injury" ~ "uninten_non_drug_inj",
    c_ind_cod_type == "Pending" ~ "pending",
  )) |>
  pivot_wider(names_from = c_ind_cod_type, values_from = count, values_fill = 0)


```

```{r}

#merging datasets 

joined_agg <- cod_agg |> 
  right_join(geo_data, join_by(c_system_abbr==system)) |>
  mutate_if(is.numeric,coalesce,0)

#writing COD into categories None/Few/Many with static cutoffs

joined_agg <- joined_agg |> 
  mutate(
    covid_19_cat = 
      case_when(
        covid_19 == 0 ~ "None",
        covid_19 >= 1 & covid_19 <= 5 ~ "Few", 
        covid_19 > 5 ~ "Many"
      ),
    drug_alc_cat = 
      case_when(
        drug_alcohol == 0 ~ "None",
        drug_alcohol >= 1 & drug_alcohol <= 5 ~ "Few", 
        drug_alcohol > 5 ~ "Many"
      ),
    natural_cat = 
      case_when(
        natural == 0 ~ "None",
        natural >= 1 & natural <= 5 ~ "Few", 
        natural > 5 ~ "Many"
      ), 
    suicide_cat = 
      case_when(
        suicide == 0 ~ "None",
        suicide >= 1 & suicide <= 5 ~ "Few", 
        suicide > 5 ~ "Many"
      ), 
    unknown_cat = 
      case_when(
        unknown == 0 ~ "None",
        unknown >= 1 & unknown <= 5 ~ "Few", 
        unknown > 5 ~ "Many"
      ),
    execution_cat = 
      case_when(
        execution == 0 ~ "None",
        execution >= 1 & execution <= 5 ~ "Few", 
        execution > 5 ~ "Many"
      ),
    homicide_cat = 
      case_when(
        homicide == 0 ~ "None",
        homicide >= 1 & homicide <= 5 ~ "Few", 
        homicide > 5 ~ "Many"
      ),
    hom_by_leo_cat = 
      case_when(
        homicide_by_leo == 0 ~ "None",
        homicide_by_leo >= 1 & homicide_by_leo <= 5 ~ "Few", 
        homicide_by_leo > 5 ~ "Many"
      ),
    nondrug_inj_cat = 
      case_when(
        uninten_non_drug_inj == 0 ~ "None",
        uninten_non_drug_inj >= 1 & uninten_non_drug_inj <= 5 ~ "Few", 
        uninten_non_drug_inj > 5 ~ "Many"
      ),
    pending_cat = 
      case_when(
        pending == 0 ~ "None",
        pending >= 1 & pending <= 5 ~ "Few", 
        pending > 5 ~ "Many"
      ))

#adding total number of COD per state (Few and Many categories together)

joined_agg <- joined_agg |> 
  mutate(tot_cod = 
           ifelse(covid_19 > 0, 1, 0) +
           ifelse(drug_alcohol > 0, 1, 0) +
           ifelse(natural > 0, 1, 0) +
           ifelse(suicide > 0, 1, 0) +
           ifelse(unknown > 0, 1, 0) +
           ifelse(execution > 0, 1, 0) +
           ifelse(homicide > 0, 1, 0) +
           ifelse(homicide_by_leo > 0, 1, 0) +
           ifelse(uninten_non_drug_inj > 0, 1, 0) +
           ifelse(pending > 0, 1, 0),
         tot_cod_cat = case_when(
           tot_cod == 0 ~ "None", 
           tot_cod > 0 & tot_cod <= 3 ~ "Low", 
           tot_cod > 3 & tot_cod <= 6 ~ "Medium", 
           tot_cod > 6 ~ "High", 
           tot_cod == 10 ~ "All"
         ))
```

```{r}
#Creating categorical variables of COD by category (Few/Many) in list form for possible tableau visualization

#COD categorized as FEW by system 
joined_agg <- joined_agg |>
  mutate(
    few_cod_per_system = ""
    ) |>
  mutate(
    few_cod_per_system = ifelse(
      covid_19_cat == "Few", 
      paste(
        few_cod_per_system, 
        "COVID-19", 
        sep = ""
        ), 
      few_cod_per_system
      )) |>
  mutate(
    few_cod_per_system = ifelse(
      drug_alc_cat == "Few", 
      paste(
        few_cod_per_system, 
        "Drug/Alcohol", 
        sep = ifelse(few_cod_per_system != "", ", ", "")
        ), 
      few_cod_per_system
      )) |>
   mutate(
     few_cod_per_system = ifelse(
       natural_cat == "Few", 
       paste(
         few_cod_per_system, 
         "Natural", 
         sep = ifelse(few_cod_per_system != "", ", ", "")
         ), 
       few_cod_per_system
       )) |>
   mutate(
     few_cod_per_system = ifelse(
       suicide_cat == "Few", 
       paste(
         few_cod_per_system, 
         "Suicide", 
         sep = ifelse(few_cod_per_system != "", ", ", "")
         ), 
       few_cod_per_system
       )) |>
   mutate(
     few_cod_per_system = ifelse(
       unknown_cat == "Few", 
       paste(
         few_cod_per_system, 
         "Unknown", 
         sep = ifelse(few_cod_per_system != "", ", ", "")
         ), 
       few_cod_per_system
       )) |>
   mutate(
     few_cod_per_system = ifelse(
       execution_cat == "Few", 
       paste(
         few_cod_per_system, 
         "Execution", 
         sep = ifelse(few_cod_per_system != "", ", ", "")
         ), 
       few_cod_per_system
       )) |>
   mutate(
     few_cod_per_system = ifelse(
       homicide_cat == "Few", 
       paste(
         few_cod_per_system, 
         "Homicide", 
         sep = ifelse(few_cod_per_system != "", ", ", "")
         ), 
       few_cod_per_system
       )) |>
   mutate(
     few_cod_per_system = ifelse(
       hom_by_leo_cat == "Few", 
       paste(
         few_cod_per_system, 
         "Homicide by LEO", 
         sep = ifelse(few_cod_per_system != "", ", ", "")
         ), 
       few_cod_per_system
       )) |>
   mutate(
     few_cod_per_system = ifelse(
       nondrug_inj_cat == "Few", 
       paste(
         few_cod_per_system, 
         "Unintentional Non-Drug Injury", 
         sep = ifelse(few_cod_per_system != "", ", ", "")
         ),
       few_cod_per_system
       )) |>
   mutate(
     few_cod_per_system = ifelse(
       pending_cat == "Few",
       paste(
         few_cod_per_system, 
         "Pending", 
         sep = ifelse(few_cod_per_system != "", ", ", "")
         ), 
       few_cod_per_system
       )) |>
  mutate(
    few_cod_per_system = ifelse(
      tot_cod == 0, 
      "None", 
      few_cod_per_system
      ))

#COD categorized as MANY by system 
joined_agg <- joined_agg |>
  mutate(
    many_cod_per_system = ""
    ) |>
  mutate(
    many_cod_per_system = ifelse(
      covid_19_cat == "Many", 
      paste(
        many_cod_per_system, 
        "COVID-19", 
        sep = ""
        ), 
      many_cod_per_system
      )) |>
  mutate(
    few_cod_per_system = ifelse(
      drug_alc_cat == "Many", 
      paste(
        many_cod_per_system, 
        "Drug/Alcohol", 
        sep = ifelse(many_cod_per_system != "", ", ", "")
        ), 
      many_cod_per_system
      )) |>
   mutate(
     many_cod_per_system = ifelse(
       natural_cat == "Many", 
       paste(
         many_cod_per_system, 
         "Natural", 
         sep = ifelse(many_cod_per_system != "", ", ", "")
         ), 
       many_cod_per_system
       )) |>
   mutate(
     many_cod_per_system = ifelse(
       suicide_cat == "Many", 
       paste(
         many_cod_per_system, 
         "Suicide", 
         sep = ifelse(many_cod_per_system != "", ", ", "")
         ), 
       many_cod_per_system
       )) |>
   mutate(
     many_cod_per_system = ifelse(
       unknown_cat == "Many", 
       paste(
         many_cod_per_system, 
         "Unknown", 
         sep = ifelse(many_cod_per_system != "", ", ", "")
         ), 
       many_cod_per_system
       )) |>
   mutate(
     many_cod_per_system = ifelse(
       execution_cat == "Many", 
       paste(
         many_cod_per_system, 
         "Execution", 
         sep = ifelse(many_cod_per_system != "", ", ", "")
         ), 
       many_cod_per_system
       )) |>
   mutate(
     many_cod_per_system = ifelse(
       homicide_cat == "Many", 
       paste(
         many_cod_per_system, 
         "Homicide", 
         sep = ifelse(many_cod_per_system != "", ", ", "")
         ), 
       many_cod_per_system
       )) |>
   mutate(
     many_cod_per_system = ifelse(
       hom_by_leo_cat == "Many", 
       paste(
         many_cod_per_system, 
         "Homicide by LEO", 
         sep = ifelse(many_cod_per_system != "", ", ", "")
         ), 
       many_cod_per_system
       )) |>
   mutate(
     many_cod_per_system = ifelse(
       nondrug_inj_cat == "Many", 
       paste(
         many_cod_per_system, 
         "Unintentional Non-Drug Injury", 
         sep = ifelse(many_cod_per_system != "", ", ", "")
         ),
       many_cod_per_system
       )) |>
   mutate(
     many_cod_per_system = ifelse(
       pending_cat == "Many",
       paste(
         many_cod_per_system, 
         "Pending", 
         sep = ifelse(many_cod_per_system != "", ", ", "")
         ), 
       many_cod_per_system
       )) |>
  mutate(
    many_cod_per_system = ifelse(
      tot_cod == 0, 
      "None", 
      many_cod_per_system
      ))

```

```{r}

#making dataset tidy for plotting
joined_agg <- joined_agg |>
  pivot_longer(cols = natural:execution, names_to = "cod_category", values_to = "counts") |>
  mutate(count_cat = case_when(
    counts == 0 ~ "None", 
    counts >= 1 & counts <= 5 ~ "Few",
    counts > 5 ~ "Many"
  )) |>
  select(-(covid_19_cat:tot_cod_cat)) 

#adding center of each system
joined_agg <- joined_agg |>
  mutate(centroid = st_centroid(geometry),
         centroid_lat = st_coordinates(centroid)[, 2],
         centroid_lon = st_coordinates(centroid)[, 1])

```

```{r}
#Editing file type for gggplot mapping as sf object
joined_agg <- joined_agg |> 
  mutate(counts_log10 = log10(counts)) |>
  st_as_sf()

##GRAPHING ALL CAUSES OF DEATH
#Not actually faceted because faceting graphs of this spatial file type warps the image

#covid_19
covid_19 <- joined_agg |>
   filter(cod_category == "covid_19") 

covid_19_no_title <- ggplot(covid_19) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

covid_19_title <- covid_19_no_title +
     labs(title = "COVID-19 deaths were only reported by the \nFederal Bureau of Prisons")  +
     theme(plot.title = element_text(size = 10, hjust = 0.5))


#drug_alcohol
drug_alc <- joined_agg |>
   filter(cod_category == "drug_alcohol") 

drug_alc_no_title <- ggplot(drug_alc) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

drug_alc_title <- drug_alc_no_title +
     labs(title = "Only South Carolina reported deaths by drug\n or alcohol ingestion", fill = "Death \nReporting Level") +
     theme(plot.title = element_text(size = 10, hjust = 0.5))


#execution
execution <- joined_agg |>
   filter(cod_category == "execution")

execution_no_title <- ggplot(execution) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

execution_title <- execution_no_title +
     labs(title = "Texas was the only system to report executions") +
     theme(plot.title = element_text(size = 10, hjust = 0.5))
  

#homicide
homicide <- joined_agg |>
   filter(cod_category == "homicide") 

homicide_no_title <- ggplot(homicide) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

homicide_title <- homicide_no_title +
     labs(title = "48 systems did not report homicides", fill = "Death \nReporting Level") +
     theme(plot.title = element_text(size = 10, hjust = 0.5))

  
#homicide_by_leo
hom_by_leo <- joined_agg |>
   filter(cod_category == "homicide_by_leo")

hom_by_leo_no_title <- ggplot(hom_by_leo) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

hom_by_leo_title <- hom_by_leo_no_title +
     labs(title = "Only four homicides by LEOs were reported") +
    theme(plot.title = element_text(size = 10, hjust = 0.5))


#natural
natural <- joined_agg |>
   filter(cod_category == "natural") 

natural_no_title <- ggplot(natural) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

natural_title <- natural_no_title +
     labs(title = "48 systems, including the Federal Bureau of Prisons, \ndo not report natural deaths")+
     theme(plot.title = element_text(size = 10, hjust = 0.5))


#pending
pending <- joined_agg |>
   filter(cod_category == "pending")

pending_no_title <- ggplot(pending) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

pending_title <- pending_no_title +
     labs(title = "Only 13 deaths classified as pending were reported", fill = "Death \nReporting Level") +
      theme(plot.title = element_text(size = 10, hjust = 0.5))



#suicide
suicide <- joined_agg |>
   filter(cod_category == "suicide") 

suicide_no_title <- ggplot(suicide) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

suicide_title <- suicide_no_title +
     labs(title = "Suicides were unreported in 47 systems") +
     theme(plot.title = element_text(size = 10, hjust = 0.5))


#uninten_non_drug_inj
uninten_non_drug_inj <- joined_agg |>
   filter(cod_category == "uninten_non_drug_inj")

uninten_non_drug_inj_no_title <- ggplot(uninten_non_drug_inj) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

uninten_non_drug_inj_title <- uninten_non_drug_inj_no_title +
     labs(title = "Florida reported all unintentional non-drug \ninjury deaths") +
     theme(plot.title = element_text(size = 10, hjust = 0.5))


#unknown
unknown <- joined_agg |>
   filter(cod_category == "unknown") 

unknown_no_title <- ggplot(unknown) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 2.2810334)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

unknown_title <- unknown_no_title +
     labs(title = "Fewer than half of all systems reported \nunknown deaths") +
     theme(plot.title = element_text(size = 10, hjust = 0.5))


```

```{r}
legend_plot <- joined_agg %>% 
  ggplot() + 
  geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) + 
  scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("None", "Few", "Many")) + 
  labs(fill = "Death Reporting Level")
custom_legend <- get_legend(legend_plot) 
legend_plot

plot_wo_title <- covid_19_no_title + drug_alc_no_title + execution_no_title + homicide_no_title + hom_by_leo_no_title + natural_no_title + pending_no_title + suicide_no_title + uninten_non_drug_inj_no_title + unknown_no_title + plot_layout(ncol = 2, nrow = 5, heights = c(1, 1)) 

combined_chloropleth_plot_wo_title <- plot_grid(plot_wo_title, custom_legend, ncol = 1, rel_heights = c(1, 0.1))
combined_chloropleth_plot_wo_title

plot <- covid_19_title + drug_alc_title + execution_title + homicide_title + hom_by_leo_title + natural_title + pending_title + suicide_title + uninten_non_drug_inj_title + unknown_title + plot_layout(ncol = 2, nrow = 5, heights = c(1, 1))
combined_chloropleth_plot <- plot_grid(plot, custom_legend, ncol = 1, rel_heights = c(1, 0.1))
combined_chloropleth_plot

path_wo_title <- here("working_doc_files", "dashboard_visualizations", "2023_cod_maps_wo_title.png")
path_w_title <- here("working_doc_files", "dashboard_visualizations", "2023_cod_maps_w_title.png") 

ggsave(path_wo_title, plot = combined_chloropleth_plot_wo_title, width = 10, height = 8, dpi = 300)
ggsave(path_w_title, plot = combined_chloropleth_plot, width = 10, height = 8, dpi = 300)
```

```{r}
#summary dataframe of year of earliest press release
min_year_sum <- agg_data |>
  separate(c_ind_dod_ymd, into = c("dod_year", "dod_month", "dod_day"), sep = "-") |>
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  ),
  dod_year = case_when(
    is.na(dod_year) & endsWith(ind_dod, "2024") ~ "2024",
    is.na(dod_year) & endsWith(ind_dod, "2023") ~ "2023",
    is.na(dod_year) & endsWith(ind_dod, "1023") ~ "2023",
    is.na(dod_year) & endsWith(ind_dod, "2022") ~ "2022",
    TRUE ~ dod_year
  )) |>
  filter(dod_year != 1950 & !is.na(dod_year)) |>
  group_by(c_system_abbr) |>
  summarize(first_year = min(dod_year),
            last_year = max(dod_year))
    
```
