---
title: "cod_chart"
author: "Project Team 2"
date: "2024-06-14"
output: html_document
---

# Load Packages

```{r}
library(tidyverse)
library(dplyr)
library(here)
```

# Load Data

```{r}
data_file_path <- here('data', 'aggregate_data.csv')
agg_data <- read_csv(data_file_path)
```

# Clean Data

```{r}
data <- data |> 
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  ))
```

# Count COD occurrences by system saved as cod_system_counts

```{r}
cod_comp = subset(agg_data, select = c(c_system_abbr, c_ind_cod_type))

cod_comp <- cod_comp |>
  group_by(c_system_abbr, c_ind_cod_type) |>
  mutate(n = n()) |>
  summarise(across(everything(), last))

write.csv(cod_comp, "../../data/cod_system_counts.csv")
```

# Calculate percentage of each COD from total number reported

```{r}
cod_comp <- cod_comp |>
  group_by(c_system_abbr) |>
  mutate(percent = (n / sum(n)) * 100) 
```

# Identify COD reported the most by systems saved as max_cod_perc

```{r}
max_cod <- cod_comp |> 
  group_by(c_system_abbr) |>
  slice(which.max(n)) |>
  select(c_system_abbr, c_ind_cod_type, n)|>
  rename(max_cod_type = c_ind_cod_type, 
         max_n = n) |>
  right_join(cod_comp)

write.csv(max_cod, "../../data/max_cod_perc.csv")
```

