---
editor_options: 
  markdown: 
    wrap: 72
  output:
  html_document:
    self_contained: false
---

```{r}
#loading packages
library(geojsonR) 
library(sf) 
library(tidyverse) 
library(ggplot2) 
library(here)
library(ggforce)
library(cowplot)
library(patchwork)
```

```{r}
#loading in data 
data_file_path <- here('data', 'aggregate_data.csv')
agg_data <- read_csv(data_file_path)


geo_file_path <- here('data', 'jurisdiction_sf.geojson')
geo_data <- st_read(geo_file_path)

st_crs(geo_data)
```

```{r}
#data wrangling cause of death data pre-join

geo_data <- geo_data |> 
  rename(system = sys_abbr)

cod_agg <- agg_data |> 
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  )) |>
  group_by(c_system_abbr, c_ind_cod_type) |> 
  summarize(count = n()) |>
  mutate(c_ind_cod_type = case_when(
    c_ind_cod_type == "COVID-19" ~ "covid_19",
    c_ind_cod_type == "Drug / Alcohol" ~ "drug_alcohol",
    c_ind_cod_type == "Natural" ~ "natural",
    c_ind_cod_type == "Suicide" ~ "suicide",
    c_ind_cod_type == "Unknown" ~ "unknown",
    c_ind_cod_type == "Execution" ~ "execution",
    c_ind_cod_type == "Homicide" ~ "homicide",
    c_ind_cod_type == "Homicide by LEO" ~ "homicide_by_leo",
    c_ind_cod_type == "Unintentional non-Drug Injury" ~ "uninten_non_drug_inj",
    c_ind_cod_type == "Pending" ~ "pending",
  )) |>
  pivot_wider(names_from = c_ind_cod_type, values_from = count, values_fill = 0)

agg_data |>
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  )) |>
  filter(!is.na(ind_link) & c_system_abbr == "DC")

min_year_sum <- agg_data |>
  separate(c_ind_dod_ymd, into = c("dod_year", "dod_month", "dod_day"), sep = "-") |>
  mutate(dod_year = case_when(
    is.na(dod_year) & endsWith(ind_dod, "2024") ~ "2024",
    is.na(dod_year) & endsWith(ind_dod, "2023") ~ "2023",
    is.na(dod_year) & endsWith(ind_dod, "1023") ~ "2023",
    is.na(dod_year) & endsWith(ind_dod, "2022") ~ "2022",
    TRUE ~ dod_year
  )) |>
  filter(dod_year != 1950 & !is.na(dod_year)) |>
  group_by(c_system_abbr) |>
  summarize(first_yr_pr = min(dod_year))

```

```{r}

#merging datasets 

joined_agg <- cod_agg |> 
  right_join(geo_data, join_by(c_system_abbr==system)) |>
  mutate_if(is.numeric,coalesce,0) |>
  left_join(min_year_sum, by = join_by(c_system_abbr == c_system_abbr))

#writing COD into categories None/Few/Many with static cutoffs
  
joined_agg <- joined_agg |> 
  mutate(
    press_release_yrs = ifelse(is.na(first_yr_pr), 1, 2024 - as.integer(first_yr_pr)),
    covid_19_cat = 
      case_when(
        covid_19 == 0 ~ "None",
        covid_19/press_release_yrs >= 1 & covid_19/press_release_yrs <= 5 ~ "Few", 
        covid_19/press_release_yrs > 5 ~ "Many"
      ),
    drug_alc_cat = 
      case_when(
        drug_alcohol == 0 ~ "None",
        drug_alcohol/press_release_yrs >= 1 & drug_alcohol/press_release_yrs <= 5 ~ "Few", 
        drug_alcohol/press_release_yrs > 5 ~ "Many"
      ),
    natural_cat = 
      case_when(
        natural == 0 ~ "None",
        natural/press_release_yrs >= 1 & natural/press_release_yrs <= 5 ~ "Few", 
        natural/press_release_yrs > 5 ~ "Many"
      ), 
    suicide_cat = 
      case_when(
        suicide == 0 ~ "None",
        suicide/press_release_yrs >= 1 & suicide/press_release_yrs <= 5 ~ "Few", 
        suicide/press_release_yrs > 5 ~ "Many"
      ), 
    unknown_cat = 
      case_when(
        unknown == 0 ~ "None",
        unknown/press_release_yrs >= 1 & unknown/press_release_yrs <= 5 ~ "Few", 
        unknown/press_release_yrs > 5 ~ "Many"
      ),
    execution_cat = 
      case_when(
        execution == 0 ~ "None",
        execution/press_release_yrs >= 1 & execution/press_release_yrs <= 5 ~ "Few", 
        execution/press_release_yrs > 5 ~ "Many"
      ),
    homicide_cat = 
      case_when(
        homicide == 0 ~ "None",
        homicide/press_release_yrs >= 1 & homicide/press_release_yrs <= 5 ~ "Few", 
        homicide/press_release_yrs > 5 ~ "Many"
      ),
    hom_by_leo_cat = 
      case_when(
        homicide_by_leo == 0 ~ "None",
        homicide_by_leo/press_release_yrs >= 1 & homicide_by_leo/press_release_yrs <= 5 ~ "Few", 
        homicide_by_leo > 5 ~ "Many"
      ),
    nondrug_inj_cat = 
      case_when(
        uninten_non_drug_inj == 0 ~ "None",
        uninten_non_drug_inj/press_release_yrs >= 1 & uninten_non_drug_inj/press_release_yrs <= 5 ~ "Few", 
        uninten_non_drug_inj/press_release_yrs > 5 ~ "Many"
      ),
    pending_cat = 
      case_when(
        pending == 0 ~ "None",
        pending/press_release_yrs >= 1 & pending/press_release_yrs <= 5 ~ "Few", 
        pending/press_release_yrs > 5 ~ "Many"
      ))

#adding total number of COD per state (Few and Many categories together)

joined_agg <- joined_agg |> 
  mutate(tot_cod = 
           ifelse(covid_19 > 0, 1, 0) +
           ifelse(drug_alcohol > 0, 1, 0) +
           ifelse(natural > 0, 1, 0) +
           ifelse(suicide > 0, 1, 0) +
           ifelse(unknown > 0, 1, 0) +
           ifelse(execution > 0, 1, 0) +
           ifelse(homicide > 0, 1, 0) +
           ifelse(homicide_by_leo > 0, 1, 0) +
           ifelse(uninten_non_drug_inj > 0, 1, 0) +
           ifelse(pending > 0, 1, 0),
         tot_cod_cat = case_when(
           tot_cod == 0 ~ "None", 
           tot_cod > 0 & tot_cod <= 3 ~ "Low", 
           tot_cod > 3 & tot_cod <= 6 ~ "Medium", 
           tot_cod > 6 ~ "High", 
           tot_cod == 10 ~ "All"
         ))
```

```{r}
#making dataset tidy for plotting

joined_agg <- joined_agg |>
  pivot_longer(cols = covid_19:pending, names_to = "cod_category", values_to = "counts") |>
  mutate(count_cat = case_when(
    counts == 0 ~ "None", 
    counts >= 1 & counts <= 5 ~ "Few",
    counts > 5 ~ "Many"
  )) |>
  select(-(covid_19_cat:tot_cod_cat)) 

#adding center of each system
joined_agg <- joined_agg |>
  mutate(centroid = st_centroid(geometry),
         centroid_lat = st_coordinates(centroid)[, 2],
         centroid_lon = st_coordinates(centroid)[, 1])

```

```{r}
#Creating logarithmic sizing scale
joined_agg <- joined_agg |> 
  mutate(counts_log10 = log10(counts)) |>
  st_as_sf()

##GRAPHING ALL CAUSES OF DEATH
#Not actually faceted because faceting graphs of this spatial file type warps the image

#covid_19
covid_19 <- joined_agg |>
   filter(cod_category == "covid_19")

covid_19_no_title <- ggplot(covid_19) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()


covid_19_title <- covid_19_no_title +
     labs(title = "COVID-19 deaths are reported in most systems\n") +
     theme(plot.title = element_text(size = 10, hjust = 0.5))



#drug_alcohol
drug_alc <- joined_agg |>
   filter(cod_category == "drug_alcohol")

drug_alc_no_title <- ggplot(drug_alc) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

drug_alc_title <- drug_alc_no_title +
  labs(title = "Only 7 systems report deaths by drug/alcohol ingestion\n") +
  theme(plot.title = element_text(size = 10, hjust = 0.5))



#execution
execution <- joined_agg |>
   filter(cod_category == "execution")

execution_no_title <- ggplot(execution) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

execution_title <- execution_no_title +
  labs(title = "Texas reports more executions than all other \nsystems combined")+
  theme(plot.title = element_text(size = 10, hjust = 0.5))


#homicide
homicide <- joined_agg |>
   filter(cod_category == "homicide")

homicide_no_title <- ggplot(homicide) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

homicide_title <- homicide_no_title +
  labs(title = "California and Florida report the most homicides\n") +
  theme(plot.title = element_text(size = 10, hjust = 0.5))
  

#homicide_by_leo
hom_by_leo <- joined_agg |>
   filter(cod_category == "homicide_by_leo") 

hom_by_leo_no_title <- ggplot(hom_by_leo) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

hom_by_leo_title <- hom_by_leo_no_title +
  labs(title = "Homicides by LEOs are only reported in four systems\n") +
  theme(plot.title = element_text(size = 10, hjust = 0.5))


#natural
natural <- joined_agg |>
   filter(cod_category == "natural")

natural_no_title <- ggplot(natural) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

natural_title <- natural_no_title +
  labs(title = "Florida reports almost all natural deaths\n") +
  theme(plot.title = element_text(size = 10, hjust = 0.5))


#pending
pending <- joined_agg |>
   filter(cod_category == "pending") 

pending_no_title <- ggplot(pending) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

pending_title <- pending_no_title +
  labs(title = "Florida and South Dakota issue almost all press \nreleases for pending death reports") +
  theme(plot.title = element_text(size = 10, hjust = 0.5))


#suicide
suicide <- joined_agg |>
   filter(cod_category == "suicide") 

suicide_no_title <- ggplot(suicide) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

suicide_title <- suicide_no_title +
  labs(title = "Suicides are unreported in 31 systems\n") +
  theme(plot.title = element_text(size = 10, hjust = 0.5))


#uninten_non_drug_inj
uninten_ndi <- joined_agg |>
   filter(cod_category == "uninten_non_drug_inj")

uninten_ndi_no_title <- ggplot(uninten_ndi) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

uninten_ndi_title <- uninten_ndi_no_title +
  labs(title = "Florida reports all but 5 unintentional non-drug \ninjury deaths") +
  theme(plot.title = element_text(size = 10, hjust = 0.5))


#unknown
unknown <- joined_agg |>
   filter(cod_category == "unknown")

unknown_no_title <- ggplot(unknown) +
   geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) +
   scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("Many", "Few", "None")) +
   geom_sf(mapping = aes(geometry = centroid, size = counts_log10)) +
   scale_size_continuous(guide = "none", limits = c(0, 3.3374593)) +
   guides(color = guide_legend(override.aes = list(size = 3)), fill = "none") +
   annotate(
     geom = "text", x = -68, y = 37, 
     label = "DC", size = 3
   ) +
   annotate("segment", x = -71, xend = -73.00002, y =37, yend = 38.89985) +
   annotate(
     geom = "text", x = -68, y = 25, 
     label = "PR", size = 3
    ) +
    annotate("segment", x = -71, xend = -73.00001, y =25, yend = 27.00015) +
    annotate(
     geom = "text", x = -93.00017, y = 23, 
     label = "BOP", size = 3
    ) +
    annotate("segment", x = -93.00017, xend = -93.00017, y =24.18, yend = 27.00001) +
    annotate(
     geom = "text", x = -83.99985, y = 23, 
     label = "ICE", size = 3
    ) +
    annotate("segment", x = -86.99985, xend = -86.99985, y =24.18, yend = 27.00012) +
    theme_void()

unknown_title <- unknown_no_title +
  labs(title = "Most states report unknown as a cause of death\n") +
  theme(plot.title = element_text(size = 10, hjust = 0.5))


```

```{r}
legend_plot <- joined_agg %>% 
  ggplot() + 
  geom_sf(mapping = aes(geometry = geometry, fill = count_cat)) + 
  scale_fill_manual(values = c("#045a8d", "#74a9cf", "#f1eef6"), breaks = c("None", "Few", "Many")) + 
  labs(fill = "Death Reporting Level")
custom_legend <- get_legend(legend_plot) 
legend_plot

plot_wo_title <- covid_19_no_title + drug_alc_no_title + execution_no_title + homicide_no_title + hom_by_leo_no_title + natural_no_title + pending_no_title + suicide_no_title + uninten_ndi_no_title + unknown_no_title + plot_layout(ncol = 2, nrow = 5, heights = c(1, 1)) 

combined_chloropleth_plot_wo_title <- plot_grid(plot_wo_title, custom_legend, ncol = 1, rel_heights = c(1, 0.1))
combined_chloropleth_plot_wo_title

plot <- covid_19_title + drug_alc_title + execution_title + homicide_title + hom_by_leo_title + natural_title + pending_title + suicide_title + uninten_ndi_title + unknown_title + plot_layout(ncol = 2, nrow = 5, heights = c(1, 1))
combined_chloropleth_plot <- plot_grid(plot, custom_legend, ncol = 1, rel_heights = c(1, 0.1))
combined_chloropleth_plot

path_wo_title <- here("working_doc_files", "dashboard_visualizations", "yearly_avg_cod_maps_wo_title.png")
path_w_title <- here("working_doc_files", "dashboard_visualizations", "yearly_avg_cod_maps_w_title.png") 

ggsave(path_wo_title, plot = combined_chloropleth_plot_wo_title, width = 10, height = 8, dpi = 300)
ggsave(path_w_title, plot = combined_chloropleth_plot, width = 10, height = 8, dpi = 300)
```

```{r}
#creating dataset for bar graph of number of systems reporting Few/Many/None for each COD
summary_cod_cutoffs <- joined_agg |>
  st_drop_geometry() |>
  group_by(cod_category, count_cat) |>
  summarize(totals = n()) |>
  select(cod_category, count_cat, totals) |>
  pivot_wider(names_from = count_cat, values_from = totals, values_fill = 0) |>
  mutate(all_passing = Few + Many)

write.csv(summary_cod_cutoffs, "../../data/summary_cod_cutoffs.csv")
#11th null ggplot into cowplot for buffer of 12th space, put legend in one of these ggplot spaces 
#Rotate legend so it goes left to right instead of up to down to fit at the bottom
#Separate plots for the website -- separate legend
```