---
title: "BJA Dataset"
author: "Amy Duan"
date: "2024-12-02"
output: html_document
---

#Library Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here) 
```

## Loading Data
```{r}
data_file_path <- here('data', 'aggregate_data.csv')
data <- read_csv(data_file_path)

data_file_path <- here('data', 'cleaner_bja_tbl.csv')
bja_data <- read_csv(data_file_path)
```

#Fixing system N/A values
```{r}
data <- data %>% 
  mutate(
    press_release_system = case_when(
      c_collection_type != "Webscrape Table" ~ str_split_fixed(file, "_", 3)[, 1],
      TRUE ~ NA_character_
    )
  ) %>% 
  mutate(
    c_system_abbr = case_when(
      c_collection_type != "Webscrape Table" & is.na(c_system_abbr) ~ press_release_system,
      TRUE ~ c_system_abbr
    )
  )
```

```{r}
missing_prison_systems <- c("IN", "MA", "MD", "ME", "MI", "ND", "NJ", "OH", "PR", "RI", "WI", "WV")

dcra_variables <- c("c_system_abbr", "c_ind_first", "c_ind_last", "c_ind_dob_year", "c_ind_gender", "c_ind_race", "c_ind_ethnicity", "c_ind_dod_year", "ind_tod", "ind_deathloc", "c_ind_fachoused", "c_ind_cod_avail")
```

#BJA Dataset Analysis/General Observations
```{r}
#Data entry dod year range
bja_years <- as.vector(unique(bja_data$cid_dod_year_int)) 
bja_years

#Data entry counts for systems that don't exist in Third City dataset
new_systems <- bja_data %>% 
  filter(state %in% missing_prison_systems) 
new_systems

#Data entry counts per system for both BJA and Third City dataset
bja_system_count <- bja_data %>% 
  group_by(state) %>% 
  count() %>% 
  mutate(system = state, 
         count_bja = n)
third_city_system_count <- data %>% 
  group_by(c_system_abbr) %>% 
  count() %>% 
  mutate(system = c_system_abbr, 
         count_third_city = n) 
system_count_totals <- full_join(bja_system_count, third_city_system_count, by = "system") %>% 
  select(system, count_bja, count_third_city) 
system_count_totals
```

```{r}
##########
# Manual entry systems tend to have more matches in the BJA dataset, whereas webscraped systems tend to have less matches in the BJA dataset (typically on the extremes - either majority or next to no entries mtached, rarely had an in-between)  
# BJA dataset contains around 4000 entries for systems that don't exist in our dataset
# BJA dataset ranges from 2019-2024 with a few junk values for years 
#
#
##########
```

#Webscraped Systems (AL, AZ, AR, CA, FL, MS, MT, TN, TX, UT)
```{r}
#AL webscraped - 0/5 entries match 
set.seed(1234)

data_al <- read_csv(here("data/webscraping_data/alabama_executions.csv"))

al_w_random_100 <- data_al %>% 
  separate(ind_dod, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day"), sep = "-") %>%
  filter(ind_dod_year %in% bja_years) %>% 
  sample_n(5) 
al_w_random_100
```

```{r}
#AZ webscraped - no entries within BJA data year range 
set.seed(1234)

data_az <- read_csv(here("data/webscraping_data/arizona_executions.csv")) 

az_w_random_100 <- data_az %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) 
az_w_random_100
```

```{r}
#AR webscraped - no entries within BJA data year range 
set.seed(1234)

data_ar <- read_csv(here("data/webscraping_data/arkansas_executions.csv")) 

ar_w_random_100 <- data_ar %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) 
ar_w_random_100
```

```{r}
#CA webscraped - no entries within BJA data year range 
set.seed(1234)

data_ca <- read_csv(here("data/webscraping_data/california_executions.csv")) 

ca_w_random_100 <- data_ca %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) 
ca_w_random_100
```

```{r}
#FL webscraped - 5/5 entries match 
set.seed(1234)

data_fl_20_21 <- read_csv(here("data/webscraping_data/florida_individual_deaths_20_21_new.csv")) 
data_fl_21_22 <- read_csv(here("data/webscraping_data/florida_individual_deaths_21_22_new.csv")) 
data_fl_22_23 <- read_csv(here("data/webscraping_data/florida_individual_deaths_22_23_new.csv")) 
data_fl_23_24 <- read_csv(here("data/webscraping_data/florida_individual_deaths_23_24_new.csv")) 

data_fl <- bind_rows(data_fl_20_21, data_fl_21_22, data_fl_22_23, data_fl_23_24)

fl_w_random_100 <- data_fl %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) %>% 
  sample_n(5)
fl_w_random_100
```

```{r}
#MS - 0/2 entries match
set.seed(1234)

data_ms <- read_csv(here("data/webscraping_data/mississippi_executions.csv")) 

ms_w_random_100 <- data_ms %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) 
ms_w_random_100
```

```{r}
# MT - 5/5 entries match
set.seed(1234)

data_mt <- read_csv(here("data/webscraping_data/montana_individual_death.csv")) 

mt_w_random_100 <- data_mt %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) %>% 
  sample_n(5)
mt_w_random_100
```

```{r}
#TN - 1/4 entries match 
set.seed(1234)

data_tn <- read_csv(here("data/webscraping_data/tennessee_executions.csv")) 

tn_w_random_100 <- data_tn %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) 
tn_w_random_100
```

```{r}
#TX - 0/5 entries match
set.seed(1234)

data_tx <- read_csv(here("data/webscraping_data/texas_executions.csv")) 

tx_w_random_100 <- data_tx %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) %>% 
  sample_n(5) 
tx_w_random_100
```

```{r}
#UT - no entries within BJA data year range
set.seed(1234)

data_ut <- read_csv(here("data/webscraping_data/utah_individual_death.csv")) 

ut_w_random_100 <- data_ut %>% 
  separate(ind_dod_ymd, into = c("ind_dod_year", "ind_dod_month", "ind_dod_day", sep = "-")) %>% 
  filter(ind_dod_year %in% bja_years) 
ut_w_random_100
```

#Manual Entry Systems
```{r}
#UT manual entry - no entries match against first and last name 
set.seed(1234)

ut_random_100 <- data %>% 
  filter(c_system_abbr == "UT") %>% 
  separate(c_ind_dod_ymd, into = c("c_ind_dod_year", "c_ind_dod_month", "c_ind_dod_day"), sep = "-") %>% 
  select(all_of(dcra_variables)) %>% 
  sample_n(10)
ut_random_100 

first_name <- tolower(as.vector(ut_random_100$c_ind_first))

bja_data %>% 
  filter(state == "UT") %>% 
  mutate(cid_full_name = tolower(cid_full_name),
         first_name_match = str_detect(cid_full_name, str_c(first_name, collapse = "|")),
         last_name_match = str_detect(cid_full_name, str_c(last_name, collapse = "|"))) %>% 
  filter(first_name_match & last_name_match) 
```

```{r}
#WY manual entry - 9/10 entries match against first and last name
set.seed(1234)

wy_random_100 <- data %>% 
  filter(c_system_abbr == "WY") %>%  
  separate(c_ind_dod_ymd, into = c("c_ind_dod_year", "c_ind_dod_month", "c_ind_dod_day"), sep = "-") %>% 
  filter(c_ind_dod_year %in% bja_years) %>% 
  select(all_of(dcra_variables)) %>% 
  sample_n(10)
wy_random_100

first_name <- tolower(as.vector(wy_random_100$c_ind_first)) 
last_name <- tolower(as.vector(wy_random_100$c_ind_last)) 

bja_data %>% 
  filter(state == "WY" | state == "IA") %>% 
  mutate(cid_full_name = tolower(cid_full_name),
         first_name_match = str_detect(cid_full_name, str_c(first_name, collapse = "|")),
         last_name_match = str_detect(cid_full_name, str_c(last_name, collapse = "|"))) %>% 
  filter(first_name_match & last_name_match) 
```

```{r}
#CA manual entry - 8/10 entries match against first and last name 
set.seed(1234) 

ca_random_100 <- data %>% 
  filter(c_system_abbr == "CA") %>%  
  separate(c_ind_dod_ymd, into = c("c_ind_dod_year", "c_ind_dod_month", "c_ind_dod_day"), sep = "-") %>% 
  filter(c_ind_dod_year %in% bja_years) %>% 
  select(all_of(dcra_variables)) %>% 
  sample_n(10)
ca_random_100 

first_name <- tolower(as.vector(ca_random_100$c_ind_first)) 
last_name <- tolower(as.vector(ca_random_100$c_ind_last)) 

bja_data %>% 
  filter(state == "CA") %>% 
  mutate(cid_full_name = tolower(cid_full_name),
         first_name_match = str_detect(cid_full_name, str_c(first_name, collapse = "|")),
         last_name_match = str_detect(cid_full_name, str_c(last_name, collapse = "|"))) %>% 
  filter(first_name_match & last_name_match) 
```

```{r}
#FL manual entry - 8/10 entries match against first and last name 
set.seed(1234) 

fl_random_100 <- data %>% 
  filter(c_system_abbr == "FL") %>%  
  separate(c_ind_dod_ymd, into = c("c_ind_dod_year", "c_ind_dod_month", "c_ind_dod_day"), sep = "-") %>% 
  filter(c_ind_dod_year %in% bja_years) %>% 
  select(all_of(dcra_variables)) %>% 
  sample_n(10)
fl_random_100 

first_name <- tolower(as.vector(fl_random_100$c_ind_first)) 
last_name <- tolower(as.vector(fl_random_100$c_ind_last)) 

bja_data %>% 
  filter(state == "FL") %>% 
  mutate(cid_full_name = tolower(cid_full_name),
         first_name_match = str_detect(cid_full_name, str_c(first_name, collapse = "|")),
         last_name_match = str_detect(cid_full_name, str_c(last_name, collapse = "|"))) %>% 
  filter(first_name_match & last_name_match) 
```

