---
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
#loading packages
library(geojsonR) 
library(sf) 
library(tidyverse) 
library(ggplot2) 
library(leaflet)
library(here)
```

```{r}
#loading in data 
data_file_path <- here('data', 'aggregate_data.csv')
agg_data <- read_csv(data_file_path)

geo_file_path <- here('data', 'jurisdiction_sf.geojson')
geo_data <- st_read(geo_file_path)

st_crs(geo_data)

geo_data |> st_centroid()

#testing map - warped? 
plot(geo_data$geometry)

#testing map - also warped
ggplot(geo_data) +
  geom_sf()

```

```{r}
#data wrangling cause of death data pre-join

geo_data <- geo_data |> 
  rename(system = sys_abbr)

cod_agg <- agg_data |> 
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  )) |>
  group_by(c_system_abbr, c_ind_cod_type) |> 
  summarize(count = n())


write.csv(cod_agg, "./boxplot_agg.csv")

ggplot(cod_agg, aes(x = c_ind_cod_type, y = count, fill = c_ind_cod_type)) + 
         geom_violin()
```

```{r}
cod_agg <- cod_agg |> 
  mutate(c_ind_cod_type = case_when(
    c_ind_cod_type == "COVID-19" ~ "covid_19",
    c_ind_cod_type == "Drug / Alcohol" ~ "drug_alcohol",
    c_ind_cod_type == "Natural" ~ "natural",
    c_ind_cod_type == "Suicide" ~ "suicide",
    c_ind_cod_type == "Unknown" ~ "unknown",
    c_ind_cod_type == "Execution" ~ "execution",
    c_ind_cod_type == "Homicide" ~ "homicide",
    c_ind_cod_type == "Homicide by LEO" ~ "homicide_by_leo",
    c_ind_cod_type == "Unintentional non-Drug Injury" ~ "uninten_non_drug_inj",
    c_ind_cod_type == "Pending" ~ "pending",
  )) |>
  pivot_wider(names_from = c_ind_cod_type, values_from = count, values_fill = 0)


```

```{r}
#creating categorical variable quantiles 

#covid_19
agg_covid_19 <- cod_agg |> 
  filter(covid_19 > 0)

covid_19_dist <- tail(quantile(agg_covid_19$covid_19), 3)

#drug_alc
agg_drug_alc <- cod_agg |> 
  filter(drug_alcohol > 0)

drug_alc_dist <- tail(quantile(agg_drug_alc$drug_alcohol), 3)

#natural
agg_natural <- cod_agg |> 
  filter(natural > 0)

natural_dist <-tail(quantile(agg_natural$natural), 3)

#suicide
agg_suicide <- cod_agg |> 
  filter(suicide > 0)

suicide_dist <- tail(quantile(agg_suicide$suicide), 3)

#unknown
agg_unknown <- cod_agg |> 
  filter(unknown > 0)

unknown_dist <- tail(quantile(agg_unknown$unknown), 3)

#execution
agg_execution <- cod_agg |> 
  filter(execution > 0)

execution_dist <- tail(quantile(agg_execution$execution), 3)

#homicide
agg_homicide <- cod_agg |> 
  filter(homicide > 0)

homicide_dist <- tail(quantile(agg_homicide$homicide), 3)

#homicide_by_leo
agg_hom_by_leo <- cod_agg |> 
  filter(homicide_by_leo > 0)

hom_by_leo_dist <- tail(quantile(agg_hom_by_leo$homicide_by_leo), 3)

#uninten_non_drug_inj
agg_nondrug_inj <- cod_agg |> 
  filter(uninten_non_drug_inj > 0)

nondrug_inj_dist <- tail(quantile(agg_nondrug_inj$uninten_non_drug_inj), 3)

#pending
agg_pending <- cod_agg |> 
  filter(pending > 0)

pending_dist <- tail(quantile(agg_pending$pending), 3)


#writing quartiles to their own file

overall_dist <- c("Low", "Medium", "High")

cod_quartile_distribution <- data.frame(covid_19_dist, drug_alc_dist, execution_dist, hom_by_leo_dist, homicide_dist, natural_dist, nondrug_inj_dist, pending_dist, suicide_dist, unknown_dist, overall_dist)

cod_quartile_distribution <- cod_quartile_distribution|>
  mutate(covid_19_dist = as.integer(covid_19_dist),
         drug_alc_dist = as.integer(drug_alc_dist),
         execution_dist = as.integer(execution_dist),
         hom_by_leo_dist = as.integer(hom_by_leo_dist),
         homicide_dist = as.integer(homicide_dist),
         natural_dist = as.integer(natural_dist),
         nondrug_inj_dist = as.integer(nondrug_inj_dist),
         pending_dist = as.integer(pending_dist),
         suicide_dist = as.integer(suicide_dist),
         unknown_dist = as.integer(unknown_dist)) |>
  pivot_longer(cols = covid_19_dist:unknown_dist, names_to = "cod_type", values_to = "cutoff") |>
  mutate(cod_type = str_remove(cod_type, '_dist'))

write.csv(cod_quartile_distribution, '../data/cod_quart_dist.csv')

```

```{r}

#merging datasets 

joined_agg <- cod_agg |> 
  right_join(geo_data, join_by(c_system_abbr==system)) |>
  mutate_if(is.numeric,coalesce,0)

#writing cod-unqiue categorical variables into dataset using non-zero quantile distribution
#bottom 50% in low, next 25% in medium, top 25% in high 
#quantile values rounded down (14.8 to 14) to represent individual deaths

joined_agg <- joined_agg |> 
  mutate(
    covid_19_cat = 
      case_when(
        covid_19 == 0 ~ "None",
        covid_19 > 0 & covid_19 < 8 ~ "Low", 
        covid_19 >= 8 & covid_19 < 14 ~ "Medium", 
        covid_19 >= 14 ~ "High"
      ),
    drug_alc_cat = 
      case_when(
        drug_alcohol == 0 ~ "None",
        drug_alcohol > 0 & drug_alcohol < 2 ~ "Low", 
        drug_alcohol == 2 ~ "Medium", 
        drug_alcohol > 2 ~ "High"
      ),
    natural_cat = 
      case_when(
        natural == 0 ~ "None",
        natural > 0 & natural < 10 ~ "Low", 
        natural >= 10 & natural < 80 ~ "Medium", 
        natural >= 80 ~ "High"
      ), 
    suicide_cat = 
      case_when(
        suicide == 0 ~ "None",
        suicide > 0 & suicide < 4 ~ "Low", 
        suicide >= 4 & suicide < 23 ~ "Medium", 
        suicide >= 23 ~ "High"
      ), 
    unknown_cat = 
      case_when(
        unknown == 0 ~ "None",
        unknown > 0 & unknown < 6 ~ "Low", 
        unknown >= 6 & unknown < 27 ~ "Medium", 
        unknown >= 27 ~ "High"
      ),
    execution_cat = 
      case_when(
        execution == 0 ~ "None",
        execution > 0 & execution < 3 ~ "Low", 
        execution >= 3 & execution < 11 ~ "Medium", 
        execution >= 11 ~ "High"
      ),
    homicide_cat = 
      case_when(
        homicide == 0 ~ "None",
        homicide > 0 & homicide < 2 ~ "Low", 
        homicide >= 2 & homicide < 8 ~ "Medium", 
        homicide >= 8 ~ "High"
      ),
    hom_by_leo_cat = 
      case_when(
        homicide_by_leo == 0 ~ "None",
        homicide_by_leo > 0 & homicide_by_leo < 2 ~ "Low", 
        homicide_by_leo >= 2 & homicide_by_leo < 4 ~ "Medium", 
        homicide_by_leo >= 4 ~ "High"
      ),
    nondrug_inj_cat = 
      case_when(
        uninten_non_drug_inj == 0 ~ "None",
        uninten_non_drug_inj > 0 & uninten_non_drug_inj < 1 ~ "Low", 
        uninten_non_drug_inj >= 1 & uninten_non_drug_inj < 23 ~ "Medium", 
        uninten_non_drug_inj >= 23 ~ "High"
      ),
    pending_cat = 
      case_when(
        pending == 0 ~ "None",
        pending > 0 & pending < 2 ~ "Low", 
        pending >= 2 & pending < 5 ~ "Medium", 
        pending >= 5 ~ "High"
      ))

#adding total number of COD per state

joined_agg <- joined_agg |> 
  mutate(tot_cod = 
           ifelse(covid_19 > 0, 1, 0) +
           ifelse(drug_alcohol > 0, 1, 0) +
           ifelse(natural > 0, 1, 0) +
           ifelse(suicide > 0, 1, 0) +
           ifelse(unknown > 0, 1, 0) +
           ifelse(execution > 0, 1, 0) +
           ifelse(homicide > 0, 1, 0) +
           ifelse(homicide_by_leo > 0, 1, 0) +
           ifelse(uninten_non_drug_inj > 0, 1, 0) +
           ifelse(pending > 0, 1, 0),
         tot_cod_cat = case_when(
           tot_cod == 0 ~ "None", 
           tot_cod > 0 & tot_cod <= 3 ~ "Low", 
           tot_cod > 3 & tot_cod <= 6 ~ "Medium", 
           tot_cod > 6 ~ "High", 
           tot_cod == 10 ~ "All"
         ))

joined_agg <- joined_agg |>
  mutate(
    non_zero_cod = ""
    ) |>
  mutate(
    non_zero_cod = ifelse(
      covid_19 > 0, 
      paste(
        non_zero_cod, 
        "COVID-19", 
        sep = ""
        ), 
      non_zero_cod
      )) |>
  mutate(
    non_zero_cod = ifelse(
      drug_alcohol > 0, 
      paste(
        non_zero_cod, 
        "Drug/Alcohol", 
        sep = ifelse(non_zero_cod != "", ", ", "")
        ), 
      non_zero_cod
      )) |>
   mutate(
     non_zero_cod = ifelse(
       natural > 0, 
       paste(
         non_zero_cod, 
         "Natural", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       suicide > 0, 
       paste(
         non_zero_cod, 
         "Suicide", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       unknown > 0, 
       paste(
         non_zero_cod, 
         "Unknown", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       execution > 0, 
       paste(
         non_zero_cod, 
         "Execution", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       homicide > 0, 
       paste(
         non_zero_cod, 
         "Homicide", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       homicide_by_leo > 0, 
       paste(
         non_zero_cod, 
         "Homicide by LEO", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       uninten_non_drug_inj > 0, 
       paste(
         non_zero_cod, 
         "Unintentional Non-Drug Injury", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ),
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       pending > 0,
       paste(
         non_zero_cod, 
         "Pending", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
  mutate(
    non_zero_cod = ifelse(
      tot_cod == 0, 
      "None", 
      non_zero_cod
      ))
  

joined_agg |> st_write("../data/joined_agg.geojson", delete_dsn = T)


```

```{r}
#graphing 
ggplot(joined_agg, aes(geometry = geometry, fill = natural_cat)) +
  geom_sf() +
  theme_minimal() 
```
