---
title: "timelines"
author: "Project Team 2"
date: "2024-06-12"
output: html_document
---

#Load Packages

```{r}
library(tidyverse)
library(dplyr)
```

#Load Data

```{r}
data_file_path <- here('data', 'aggregate_data.csv')
data <- read_csv(data_file_path)

data <- data |> 
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  ))
```

# Create count variable by year

```{r}
agg_data <- data |>
  drop_na(c_ind_dod_ymd) |>
  separate(c_ind_dod_ymd, into = c("dod_year", "dod_month", "dod_day"), sep = "-") |>
  group_by(dod_year) |>
  mutate(n = n()) 
```


# Create final tibble with count

```{r}
releases_comp = subset(agg_data, select = c(dod_year, n))

releases_comp <- releases_comp |>
  group_by(dod_year) |>
  summarise(across(everything(), last))

write.csv(releases_comp, "releases_timeline.csv")
```


# Create system variable by year

```{r}
system_count_data <- system_count_data |>
  group_by(dod_year, c_system_abbr) |>
  mutate(n = n())
```


# Create final tibble with relevant counts

```{r}
system_release_comp = subset(system_count_data, select = c(dod_year, c_system_abbr, n))

system_release_comp <- system_release_comp |>
  group_by(dod_year, c_system_abbr) |>
  summarise(across(everything(), last))

write.csv(system_release_comp, "system_releases_timeline.csv")
```

# Count number of systems that report per year

```{r}
system_release_comp <- system_release_comp |>
  group_by(dod_year) |>
  mutate(system_count = n())
```

# Create final tibble with number of systems that report per year

```{r}
system_count_comp = subset(system_release_comp, select = c(dod_year,system_count))

system_count_comp <- system_count_comp |>
  group_by(dod_year) |>
  summarise(across(everything(), last))

write.csv(system_count_comp, "system_count_timeline.csv")
```

