---
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
#loading packages
library(geojsonR) 
library(sf) 
library(tidyverse) 
library(ggplot2) 
library(leaflet)
library(here)
```

```{r}
#loading in data 
data_file_path <- here('data', 'aggregate_data.csv')
agg_data <- read_csv(data_file_path)

geo_file_path <- here('data', 'jurisdiction_sf.geojson')
geo_data <- st_read(geo_file_path)

st_crs(geo_data)
```

```{r}
#data wrangling cause of death data pre-join

geo_data <- geo_data |> 
  rename(system = sys_abbr)

cod_agg <- agg_data |> 
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  )) |>
  group_by(c_system_abbr, c_ind_cod_type) |> 
  summarize(count = n())


write.csv(cod_agg, "./boxplot_agg.csv")

ggplot(cod_agg, aes(x = c_ind_cod_type, y = count, fill = c_ind_cod_type)) + 
         geom_violin()
```

```{r}
cod_agg <- cod_agg |> 
  mutate(c_ind_cod_type = case_when(
    c_ind_cod_type == "COVID-19" ~ "covid_19",
    c_ind_cod_type == "Drug / Alcohol" ~ "drug_alcohol",
    c_ind_cod_type == "Natural" ~ "natural",
    c_ind_cod_type == "Suicide" ~ "suicide",
    c_ind_cod_type == "Unknown" ~ "unknown",
    c_ind_cod_type == "Execution" ~ "execution",
    c_ind_cod_type == "Homicide" ~ "homicide",
    c_ind_cod_type == "Homicide by LEO" ~ "homicide_by_leo",
    c_ind_cod_type == "Unintentional non-Drug Injury" ~ "uninten_non_drug_inj",
    c_ind_cod_type == "Pending" ~ "pending",
  )) |>
  pivot_wider(names_from = c_ind_cod_type, values_from = count, values_fill = 0)


```

```{r}
#creating categorical variable quantiles 

#covid_19
agg_covid_19 <- cod_agg |> 
  filter(covid_19 > 0)

covid_19_dist <- tail(quantile(agg_covid_19$covid_19), 3)

#drug_alc
agg_drug_alc <- cod_agg |> 
  filter(drug_alcohol > 0)

drug_alc_dist <- tail(quantile(agg_drug_alc$drug_alcohol), 3)

#natural
agg_natural <- cod_agg |> 
  filter(natural > 0)

natural_dist <-tail(quantile(agg_natural$natural), 3)

#suicide
agg_suicide <- cod_agg |> 
  filter(suicide > 0)

suicide_dist <- tail(quantile(agg_suicide$suicide), 3)

#unknown
agg_unknown <- cod_agg |> 
  filter(unknown > 0)

unknown_dist <- tail(quantile(agg_unknown$unknown), 3)

#execution
agg_execution <- cod_agg |> 
  filter(execution > 0)

execution_dist <- tail(quantile(agg_execution$execution), 3)

#homicide
agg_homicide <- cod_agg |> 
  filter(homicide > 0)

homicide_dist <- tail(quantile(agg_homicide$homicide), 3)

#homicide_by_leo
agg_hom_by_leo <- cod_agg |> 
  filter(homicide_by_leo > 0)

hom_by_leo_dist <- tail(quantile(agg_hom_by_leo$homicide_by_leo), 3)

#uninten_non_drug_inj
agg_nondrug_inj <- cod_agg |> 
  filter(uninten_non_drug_inj > 0)

nondrug_inj_dist <- tail(quantile(agg_nondrug_inj$uninten_non_drug_inj), 3)

#pending
agg_pending <- cod_agg |> 
  filter(pending > 0)

pending_dist <- tail(quantile(agg_pending$pending), 3)


#writing quartiles to their own file

overall_dist <- c("Low", "Medium", "High")

cod_quartile_distribution <- data.frame(covid_19_dist, drug_alc_dist, execution_dist, hom_by_leo_dist, homicide_dist, natural_dist, nondrug_inj_dist, pending_dist, suicide_dist, unknown_dist, overall_dist)

cod_quartile_distribution <- cod_quartile_distribution|>
  mutate(covid_19_dist = as.integer(covid_19_dist),
         drug_alc_dist = as.integer(drug_alc_dist),
         execution_dist = as.integer(execution_dist),
         hom_by_leo_dist = as.integer(hom_by_leo_dist),
         homicide_dist = as.integer(homicide_dist),
         natural_dist = as.integer(natural_dist),
         nondrug_inj_dist = as.integer(nondrug_inj_dist),
         pending_dist = as.integer(pending_dist),
         suicide_dist = as.integer(suicide_dist),
         unknown_dist = as.integer(unknown_dist)) |>
  pivot_longer(cols = covid_19_dist:unknown_dist, names_to = "cod_type", values_to = "cutoff") |>
  mutate(cod_type = str_remove(cod_type, '_dist'))

write.csv(cod_quartile_distribution, '../data/cod_quart_dist.csv')

```

```{r}

#merging datasets 

joined_agg <- cod_agg |> 
  right_join(geo_data, join_by(c_system_abbr==system)) |>
  mutate_if(is.numeric,coalesce,0)

#writing cod-unqiue categorical variables into dataset using non-zero quantile distribution
#bottom 50% in low, next 25% in medium, top 25% in high 
#quantile values rounded down (14.8 to 14) to represent individual deaths

joined_agg <- joined_agg |> 
  mutate(
    covid_19_cat = 
      case_when(
        covid_19 == 0 ~ "None",
        covid_19 > 0 & covid_19 < 8 ~ "Low", 
        covid_19 >= 8 & covid_19 < 14 ~ "Medium", 
        covid_19 >= 14 ~ "High"
      ),
    drug_alc_cat = 
      case_when(
        drug_alcohol == 0 ~ "None",
        drug_alcohol > 0 & drug_alcohol < 2 ~ "Low", 
        drug_alcohol == 2 ~ "Medium", 
        drug_alcohol > 2 ~ "High"
      ),
    natural_cat = 
      case_when(
        natural == 0 ~ "None",
        natural > 0 & natural < 10 ~ "Low", 
        natural >= 10 & natural < 80 ~ "Medium", 
        natural >= 80 ~ "High"
      ), 
    suicide_cat = 
      case_when(
        suicide == 0 ~ "None",
        suicide > 0 & suicide < 4 ~ "Low", 
        suicide >= 4 & suicide < 23 ~ "Medium", 
        suicide >= 23 ~ "High"
      ), 
    unknown_cat = 
      case_when(
        unknown == 0 ~ "None",
        unknown > 0 & unknown < 6 ~ "Low", 
        unknown >= 6 & unknown < 27 ~ "Medium", 
        unknown >= 27 ~ "High"
      ),
    execution_cat = 
      case_when(
        execution == 0 ~ "None",
        execution > 0 & execution < 3 ~ "Low", 
        execution >= 3 & execution < 11 ~ "Medium", 
        execution >= 11 ~ "High"
      ),
    homicide_cat = 
      case_when(
        homicide == 0 ~ "None",
        homicide > 0 & homicide < 2 ~ "Low", 
        homicide >= 2 & homicide < 8 ~ "Medium", 
        homicide >= 8 ~ "High"
      ),
    hom_by_leo_cat = 
      case_when(
        homicide_by_leo == 0 ~ "None",
        homicide_by_leo > 0 & homicide_by_leo < 2 ~ "Low", 
        homicide_by_leo >= 2 & homicide_by_leo < 4 ~ "Medium", 
        homicide_by_leo >= 4 ~ "High"
      ),
    nondrug_inj_cat = 
      case_when(
        uninten_non_drug_inj == 0 ~ "None",
        uninten_non_drug_inj > 0 & uninten_non_drug_inj < 1 ~ "Low", 
        uninten_non_drug_inj >= 1 & uninten_non_drug_inj < 23 ~ "Medium", 
        uninten_non_drug_inj >= 23 ~ "High"
      ),
    pending_cat = 
      case_when(
        pending == 0 ~ "None",
        pending > 0 & pending < 2 ~ "Low", 
        pending >= 2 & pending < 5 ~ "Medium", 
        pending >= 5 ~ "High"
      ))

#adding total number of COD per state

joined_agg <- joined_agg |> 
  mutate(tot_cod = 
           ifelse(covid_19 > 0, 1, 0) +
           ifelse(drug_alcohol > 0, 1, 0) +
           ifelse(natural > 0, 1, 0) +
           ifelse(suicide > 0, 1, 0) +
           ifelse(unknown > 0, 1, 0) +
           ifelse(execution > 0, 1, 0) +
           ifelse(homicide > 0, 1, 0) +
           ifelse(homicide_by_leo > 0, 1, 0) +
           ifelse(uninten_non_drug_inj > 0, 1, 0) +
           ifelse(pending > 0, 1, 0),
         tot_cod_cat = case_when(
           tot_cod == 0 ~ "None", 
           tot_cod > 0 & tot_cod <= 3 ~ "Low", 
           tot_cod > 3 & tot_cod <= 6 ~ "Medium", 
           tot_cod > 6 ~ "High", 
           tot_cod == 10 ~ "All"
         ))

joined_agg <- joined_agg |>
  mutate(
    non_zero_cod = ""
    ) |>
  mutate(
    non_zero_cod = ifelse(
      covid_19 > 0, 
      paste(
        non_zero_cod, 
        "COVID-19", 
        sep = ""
        ), 
      non_zero_cod
      )) |>
  mutate(
    non_zero_cod = ifelse(
      drug_alcohol > 0, 
      paste(
        non_zero_cod, 
        "Drug/Alcohol", 
        sep = ifelse(non_zero_cod != "", ", ", "")
        ), 
      non_zero_cod
      )) |>
   mutate(
     non_zero_cod = ifelse(
       natural > 0, 
       paste(
         non_zero_cod, 
         "Natural", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       suicide > 0, 
       paste(
         non_zero_cod, 
         "Suicide", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       unknown > 0, 
       paste(
         non_zero_cod, 
         "Unknown", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       execution > 0, 
       paste(
         non_zero_cod, 
         "Execution", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       homicide > 0, 
       paste(
         non_zero_cod, 
         "Homicide", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       homicide_by_leo > 0, 
       paste(
         non_zero_cod, 
         "Homicide by LEO", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       uninten_non_drug_inj > 0, 
       paste(
         non_zero_cod, 
         "Unintentional Non-Drug Injury", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ),
       non_zero_cod
       )) |>
   mutate(
     non_zero_cod = ifelse(
       pending > 0,
       paste(
         non_zero_cod, 
         "Pending", 
         sep = ifelse(non_zero_cod != "", ", ", "")
         ), 
       non_zero_cod
       )) |>
  mutate(
    non_zero_cod = ifelse(
      tot_cod == 0, 
      "None", 
      non_zero_cod
      ))


```

```{r}
#creating dataset with coordinates of centers of each object
state_centers <- joined_agg |>
  mutate(centroid = st_centroid(geometry),
         centroid_lat = st_coordinates(centroid)[, 2],
         centroid_lon = st_coordinates(centroid)[, 1])

state_centers |> st_write("../data/joined_agg.geojson", delete_dsn = T)
```

```{r}
#adjust all bubble plots to have same scale?

joined_agg <- joined_agg |> 
  st_as_sf()

#execution bubble plot
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = execution, color = execution_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "Texas reports more executions than all other systems combined", color = "Execution \nreporting level") + 
  theme_void() 

#homicide bubble plot
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = homicide, color = homicide_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "California and Florida report the most homicides", color = "Homicide \nreporting level") + 
  theme_void()

#homicide by LEO bubble plot
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = homicide_by_leo, color = hom_by_leo_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "Homicides by LEOs are only reported in four systems", color = "Homicide by LEO \nreporting level") + 
  theme_void()

#natural bubble plot
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = natural, color = natural_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "Florida reports almost all natural deaths", color = "Natural death \nreporting level") + 
  theme_void()

#unknown bubble plot
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = unknown, color = unknown_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "Most states report unknown causes of death", color = "Homicide \nreporting level") + 
  theme_void()

#pending bubble plot
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = pending, color = pending_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "Florida and South Dakota issue almost all press releases for pending death reports", color = "Pending \nreporting level") +
  theme_void()

#covid-19 bubble plot 
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = covid_19, color = covid_19_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "COVID-19 deaths are reported in most systems", color = "COVID-19 \nreporting level") +
  theme_void()

#suicide bubble plot 
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = suicide, color = suicide_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "Suicides are unreported in 31 systems", color = "Suicide \nreporting level") +
  theme_void()

#unintentional non-drug injury bubble plot
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = uninten_non_drug_inj, color = nondrug_inj_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "Florida reports all but 5 unintentional non-drug injury deaths", color = "Unintentional non-drug injury \nreporting level") +
  theme_void()

#drug/alcohol bubble plot
ggplot() +
  geom_sf(joined_agg, mapping = aes(geometry = geometry), fill = "gray95") +
  geom_sf(centers, mapping = aes(geometry = latlong, size = drug_alcohol, color = drug_alc_cat)) +
  scale_size_continuous(range = c(-1, 12), guide = "none") +
  scale_colour_manual(values = c("dodgerblue4", "dodgerblue3", "darkcyan", "white"), breaks = c("High", "Medium", "Low")) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(title = "Only 7 systems report deaths by drug/alcohol ingestion", color = "Drug/alcohol \nreporting level") +
  theme_void()

```

```{r}
#summary dataframe of year of earliest press release
min_year_sum <- agg_data |>
  separate(c_ind_dod_ymd, into = c("dod_year", "dod_month", "dod_day"), sep = "-") |>
  mutate(c_system_abbr = case_when(
    startsWith(file, "FL") ~ "FL", 
    startsWith(file, "AZ") ~ "AZ",
    startsWith(file, "DE") ~ "DE", 
    startsWith(file, "IA") ~ "IA",
    TRUE ~ c_system_abbr
  ),
  dod_year = case_when(
    endsWith(file, "2015.csv") ~ "2015",
    endsWith(file, "2020.csv") ~ "2020",
    endsWith(file, "1999.csv") ~ "1999",
    endsWith(file, "2017.csv") ~ "2017",
    endsWith(file, "2014.csv") ~ "2014", 
    TRUE ~ dod_year
  )) |>
  filter(dod_year != 1950) |>
  group_by(c_system_abbr) |>
  summarize(first_year = min(dod_year))
    
```

```{r}
#creating dataset with causes of death as observations and cutoffs
cod_cutoff_file_path <- here('data', 'cod_cutoffs.csv')
cod_cutoff <- read_csv(cod_cutoff_file_path)

passing_cutoffs <- cod_agg |> 
  right_join(cod_cutoff, join_by(c_system_abbr==system)) |> 
  mutate(execution = ifelse(execution_est == 0, 0, TRUE))

#determine cause of death reporting status, standardized across years
passing_cutoffs <- passing_cutoffs |> 
  pivot_longer(cols = covid_19:pending, names_to = "cod_category", values_to = "totals") |>
  mutate(press_release_yrs = 2024 - first_yr_pr,
         estimates = case_when(
           cod_category == "covid_19" ~ covid_19_est,
           cod_category == "suicide" ~ suicide_est,
           cod_category == "execution" ~ execution_est,
           cod_category == "natural" ~ natural_est,
           cod_category == "pending" ~ pending_est,
           cod_category == "unknown" ~ unknown_est,
           cod_category == "uninten_non_drug_inj" ~ uninten_non_drug_inj_est,
           cod_category == "drug_alcohol" ~ drug_alc_est,
           cod_category == "homicide" ~ homicide_est,
           cod_category == "homicide_by_leo" ~ hom_by_leo_est
         ),
         pass_status = ifelse((totals/press_release_yrs) >= estimates, "Yes", "No"))

#creating variables for the maximum and minimum number of reports per system per pass status (way of demonstrating range within pass status by COD)
max_min_passing <- passing_cutoffs |> 
  mutate(pass_status = case_when(
    totals == 0 & (cod_category != "execution") ~ "No Data", 
    pass_status == "Yes" ~ "Reporting",
    pass_status == "No"  ~ "Underreporting")) |>
  filter(pass_status == "Reporting") |> 
  group_by(cod_category) |> 
  summarize(max = max(totals),
            min = min(totals)) |>
  mutate(pass_status = "Reporting")

#creating dataset for total counts of systems by cause of death and pass status
summary_cod_cutoffs <- passing_cutoffs |> 
  mutate(pass_status = case_when(
    totals == 0 & (cod_category != "execution") ~ "No Data", 
    pass_status == "Yes" ~ "Reporting",
    pass_status == "No"  ~ "Underreporting")) |>
  group_by(cod_category, pass_status) |>
  summarize(totals = n())

#merging counts and pass status + COD max/min counts
summary_cod_cutoffs <- summary_cod_cutoffs|>
  left_join(max_min_passing, by = join_by(cod_category, pass_status))

#writing CSV to folder
write.csv(summary_cod_cutoffs, "../data/summary_cod_cutoffs.csv")

#quick plot to check
summary_cod_cutoffs |> 
  filter(pass_status == "Reporting") |>
  ggplot(aes(x = totals, y = cod_category)) +
  geom_col() +
  theme_minimal() + 
  xlim(0, 54)

```